version = 3.9.4
runner.dialect = scala3

maxColumn = 100
newlines.source = keep
newlines.alwaysBeforeElseAfterCurlyIf = true
newlines.forceBeforeMultilineAssign = def
danglingParentheses.defnSite = true
binPack.literalsExclude = []
binPack.literalsIncludeSimpleExpr = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true

project.excludePaths = [
  "glob:**/src/main/scala/util/multicodec.scala"
]
