package multiformats

import multiformats.varint.VarInt

final case class MulticodecValidationError(
    private val message: String = "",
    private val cause: Throwable = None.orNull
) extends Exception(message, cause)

object multicodec:

  // format: off
  // generateMulticodec: begin //
  enum MulticodecTag:
    case cid
    case encryption
    case filecoin
    case hash
    case holochain
    case ipld
    case key
    case libp2p
    case multiaddr
    case multiformat
    case multihash
    case multikey
    case multisig
    case namespace
    case nonce
    case serialization
    case shelter
    case softhash
    case transport
    case varsig
    case vlad
    case zeroxcert

  enum MulticodecStatus:
    case deprecated, draft, permanent

  enum Multicodec(val tag: MulticodecTag, val code: VarInt, val status: MulticodecStatus, val description: Option[String]):
    case identity                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x00), MulticodecStatus.permanent, Some("raw binary"))
    case cidv1                          extends Multicodec(MulticodecTag.cid, VarInt.encode(0x01), MulticodecStatus.permanent, Some("CIDv1"))
    case cidv2                          extends Multicodec(MulticodecTag.cid, VarInt.encode(0x02), MulticodecStatus.draft, Some("CIDv2"))
    case cidv3                          extends Multicodec(MulticodecTag.cid, VarInt.encode(0x03), MulticodecStatus.draft, Some("CIDv3"))
    case ip4                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x04), MulticodecStatus.permanent, None)
    case tcp                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x06), MulticodecStatus.permanent, None)
    case sha1                           extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x11), MulticodecStatus.permanent, None)
    case sha2_256                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x12), MulticodecStatus.permanent, None)
    case sha2_512                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x13), MulticodecStatus.permanent, None)
    case sha3_512                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x14), MulticodecStatus.permanent, None)
    case sha3_384                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x15), MulticodecStatus.permanent, None)
    case sha3_256                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x16), MulticodecStatus.permanent, None)
    case sha3_224                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x17), MulticodecStatus.permanent, None)
    case shake_128                      extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x18), MulticodecStatus.draft, None)
    case shake_256                      extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x19), MulticodecStatus.draft, None)
    case keccak_224                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1a), MulticodecStatus.draft, Some("keccak has variable output length. The number specifies the core length"))
    case keccak_256                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1b), MulticodecStatus.draft, None)
    case keccak_384                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1c), MulticodecStatus.draft, None)
    case keccak_512                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1d), MulticodecStatus.draft, None)
    case blake3                         extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1e), MulticodecStatus.draft, Some("BLAKE3 has a default 32 byte output length. The maximum length is (2^64)-1 bytes."))
    case sha2_384                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x20), MulticodecStatus.permanent, Some("aka SHA-384; as specified by FIPS 180-4."))
    case dccp                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x21), MulticodecStatus.draft, None)
    case murmur3_x64_64                 extends Multicodec(MulticodecTag.hash, VarInt.encode(0x22), MulticodecStatus.permanent, Some("The first 64-bits of a murmur3-x64-128 - used for UnixFS directory sharding."))
    case murmur3_32                     extends Multicodec(MulticodecTag.hash, VarInt.encode(0x23), MulticodecStatus.draft, None)
    case ip6                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x29), MulticodecStatus.permanent, None)
    case ip6zone                        extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x2a), MulticodecStatus.draft, None)
    case ipcidr                         extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x2b), MulticodecStatus.draft, Some("CIDR mask for IP addresses"))
    case path                           extends Multicodec(MulticodecTag.namespace, VarInt.encode(0x2f), MulticodecStatus.permanent, Some("Namespace for string paths. Corresponds to `/` in ASCII."))
    case multicodec                     extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x30), MulticodecStatus.draft, None)
    case multihash                      extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x31), MulticodecStatus.draft, None)
    case multiaddr                      extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x32), MulticodecStatus.draft, None)
    case multibase                      extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x33), MulticodecStatus.draft, None)
    case varsig                         extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x34), MulticodecStatus.draft, Some("Variable signature (varsig) multiformat"))
    case dns                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x35), MulticodecStatus.permanent, None)
    case dns4                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x36), MulticodecStatus.permanent, None)
    case dns6                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x37), MulticodecStatus.permanent, None)
    case dnsaddr                        extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x38), MulticodecStatus.permanent, None)
    case protobuf                       extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x50), MulticodecStatus.draft, Some("Protocol Buffers"))
    case cbor                           extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x51), MulticodecStatus.permanent, Some("CBOR"))
    case raw                            extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x55), MulticodecStatus.permanent, Some("raw binary"))
    case dbl_sha2_256                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x56), MulticodecStatus.draft, None)
    case rlp                            extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x60), MulticodecStatus.draft, Some("recursive length prefix"))
    case bencode                        extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x63), MulticodecStatus.draft, Some("bencode"))
    case dag_pb                         extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x70), MulticodecStatus.permanent, Some("MerkleDAG protobuf"))
    case dag_cbor                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x71), MulticodecStatus.permanent, Some("MerkleDAG cbor"))
    case libp2p_key                     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x72), MulticodecStatus.permanent, Some("Libp2p Public Key"))
    case git_raw                        extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x78), MulticodecStatus.permanent, Some("Raw Git object"))
    case torrent_info                   extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x7b), MulticodecStatus.draft, Some("Torrent file info field (bencoded)"))
    case torrent_file                   extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x7c), MulticodecStatus.draft, Some("Torrent file (bencoded)"))
    case blake3_hashseq                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x80), MulticodecStatus.draft, Some("BLAKE3 hash sequence - per Iroh collections spec"))
    case leofcoin_block                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x81), MulticodecStatus.draft, Some("Leofcoin Block"))
    case leofcoin_tx                    extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x82), MulticodecStatus.draft, Some("Leofcoin Transaction"))
    case leofcoin_pr                    extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x83), MulticodecStatus.draft, Some("Leofcoin Peer Reputation"))
    case sctp                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x84), MulticodecStatus.draft, None)
    case dag_jose                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x85), MulticodecStatus.draft, Some("MerkleDAG JOSE"))
    case dag_cose                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x86), MulticodecStatus.draft, Some("MerkleDAG COSE"))
    case lbry                           extends Multicodec(MulticodecTag.namespace, VarInt.encode(0x8c), MulticodecStatus.draft, Some("LBRY Address"))
    case eth_block                      extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x90), MulticodecStatus.permanent, Some("Ethereum Header (RLP)"))
    case eth_block_list                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x91), MulticodecStatus.permanent, Some("Ethereum Header List (RLP)"))
    case eth_tx_trie                    extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x92), MulticodecStatus.permanent, Some("Ethereum Transaction Trie (Eth-Trie)"))
    case eth_tx                         extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x93), MulticodecStatus.permanent, Some("Ethereum Transaction (MarshalBinary)"))
    case eth_tx_receipt_trie            extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x94), MulticodecStatus.permanent, Some("Ethereum Transaction Receipt Trie (Eth-Trie)"))
    case eth_tx_receipt                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x95), MulticodecStatus.permanent, Some("Ethereum Transaction Receipt (MarshalBinary)"))
    case eth_state_trie                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x96), MulticodecStatus.permanent, Some("Ethereum State Trie (Eth-Secure-Trie)"))
    case eth_account_snapshot           extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x97), MulticodecStatus.permanent, Some("Ethereum Account Snapshot (RLP)"))
    case eth_storage_trie               extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x98), MulticodecStatus.permanent, Some("Ethereum Contract Storage Trie (Eth-Secure-Trie)"))
    case eth_receipt_log_trie           extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x99), MulticodecStatus.draft, Some("Ethereum Transaction Receipt Log Trie (Eth-Trie)"))
    case eth_receipt_log                extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x9a), MulticodecStatus.draft, Some("Ethereum Transaction Receipt Log (RLP)"))
    case aes_128                        extends Multicodec(MulticodecTag.key, VarInt.encode(0xa0), MulticodecStatus.draft, Some("128-bit AES symmetric key"))
    case aes_192                        extends Multicodec(MulticodecTag.key, VarInt.encode(0xa1), MulticodecStatus.draft, Some("192-bit AES symmetric key"))
    case aes_256                        extends Multicodec(MulticodecTag.key, VarInt.encode(0xa2), MulticodecStatus.draft, Some("256-bit AES symmetric key"))
    case chacha_128                     extends Multicodec(MulticodecTag.key, VarInt.encode(0xa3), MulticodecStatus.draft, Some("128-bit ChaCha symmetric key"))
    case chacha_256                     extends Multicodec(MulticodecTag.key, VarInt.encode(0xa4), MulticodecStatus.draft, Some("256-bit ChaCha symmetric key"))
    case bitcoin_block                  extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xb0), MulticodecStatus.permanent, Some("Bitcoin Block"))
    case bitcoin_tx                     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xb1), MulticodecStatus.permanent, Some("Bitcoin Tx"))
    case bitcoin_witness_commitment     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xb2), MulticodecStatus.permanent, Some("Bitcoin Witness Commitment"))
    case zcash_block                    extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xc0), MulticodecStatus.permanent, Some("Zcash Block"))
    case zcash_tx                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xc1), MulticodecStatus.permanent, Some("Zcash Tx"))
    case caip_50                        extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0xca), MulticodecStatus.draft, Some("CAIP-50 multi-chain account ID"))
    case streamid                       extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xce), MulticodecStatus.draft, Some("Ceramic Stream ID"))
    case stellar_block                  extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xd0), MulticodecStatus.draft, Some("Stellar Block"))
    case stellar_tx                     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xd1), MulticodecStatus.draft, Some("Stellar Tx"))
    case md4                            extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xd4), MulticodecStatus.draft, None)
    case md5                            extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xd5), MulticodecStatus.draft, None)
    case decred_block                   extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xe0), MulticodecStatus.draft, Some("Decred Block"))
    case decred_tx                      extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xe1), MulticodecStatus.draft, Some("Decred Tx"))
    case ipld                           extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe2), MulticodecStatus.draft, Some("IPLD path"))
    case ipfs                           extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe3), MulticodecStatus.draft, Some("IPFS path"))
    case swarm                          extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe4), MulticodecStatus.draft, Some("Swarm path"))
    case ipns                           extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe5), MulticodecStatus.draft, Some("IPNS path"))
    case zeronet                        extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe6), MulticodecStatus.draft, Some("ZeroNet site address"))
    case secp256k1_pub                  extends Multicodec(MulticodecTag.key, VarInt.encode(0xe7), MulticodecStatus.draft, Some("Secp256k1 public key (compressed)"))
    case dnslink                        extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xe8), MulticodecStatus.permanent, Some("DNSLink path"))
    case bls12_381_g1_pub               extends Multicodec(MulticodecTag.key, VarInt.encode(0xea), MulticodecStatus.draft, Some("BLS12-381 public key in the G1 field"))
    case bls12_381_g2_pub               extends Multicodec(MulticodecTag.key, VarInt.encode(0xeb), MulticodecStatus.draft, Some("BLS12-381 public key in the G2 field"))
    case x25519_pub                     extends Multicodec(MulticodecTag.key, VarInt.encode(0xec), MulticodecStatus.draft, Some("Curve25519 public key"))
    case ed25519_pub                    extends Multicodec(MulticodecTag.key, VarInt.encode(0xed), MulticodecStatus.draft, Some("Ed25519 public key"))
    case bls12_381_g1g2_pub             extends Multicodec(MulticodecTag.key, VarInt.encode(0xee), MulticodecStatus.draft, Some("BLS12-381 concatenated public keys in both the G1 and G2 fields"))
    case sr25519_pub                    extends Multicodec(MulticodecTag.key, VarInt.encode(0xef), MulticodecStatus.draft, Some("Sr25519 public key"))
    case dash_block                     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xf0), MulticodecStatus.draft, Some("Dash Block"))
    case dash_tx                        extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xf1), MulticodecStatus.draft, Some("Dash Tx"))
    case swarm_manifest                 extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xfa), MulticodecStatus.draft, Some("Swarm Manifest"))
    case swarm_feed                     extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xfb), MulticodecStatus.draft, Some("Swarm Feed"))
    case beeson                         extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xfc), MulticodecStatus.draft, Some("Swarm BeeSon"))
    case udp                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0111), MulticodecStatus.draft, None)
    case p2p_webrtc_star                extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0113), MulticodecStatus.deprecated, Some("Use webrtc or webrtc-direct instead"))
    case p2p_webrtc_direct              extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0114), MulticodecStatus.deprecated, Some("Use webrtc or webrtc-direct instead"))
    case p2p_stardust                   extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0115), MulticodecStatus.deprecated, None)
    case webrtc_direct                  extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0118), MulticodecStatus.draft, Some("ICE-lite webrtc transport with SDP munging during connection establishment and without use of a STUN server"))
    case webrtc                         extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0119), MulticodecStatus.draft, Some("webrtc transport where connection establishment is according to w3c spec"))
    case p2p_circuit                    extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0122), MulticodecStatus.permanent, None)
    case dag_json                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x0129), MulticodecStatus.permanent, Some("MerkleDAG json"))
    case udt                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x012d), MulticodecStatus.draft, None)
    case utp                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x012e), MulticodecStatus.draft, None)
    case crc32                          extends Multicodec(MulticodecTag.hash, VarInt.encode(0x0132), MulticodecStatus.draft, Some("CRC-32 non-cryptographic hash algorithm (IEEE 802.3)"))
    case crc64_ecma                     extends Multicodec(MulticodecTag.hash, VarInt.encode(0x0164), MulticodecStatus.draft, Some("CRC-64 non-cryptographic hash algorithm (ECMA-182 - Annex B)"))
    case unix                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0190), MulticodecStatus.permanent, None)
    case thread                         extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x0196), MulticodecStatus.draft, Some("Textile Thread"))
    case p2p                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01a5), MulticodecStatus.permanent, Some("libp2p"))
    case https                          extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01bb), MulticodecStatus.draft, None)
    case onion                          extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01bc), MulticodecStatus.draft, None)
    case onion3                         extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01bd), MulticodecStatus.draft, None)
    case garlic64                       extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01be), MulticodecStatus.draft, Some("I2P base64 (raw public key)"))
    case garlic32                       extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01bf), MulticodecStatus.draft, Some("I2P base32 (hashed public key or encoded public key/checksum+optional secret)"))
    case tls                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01c0), MulticodecStatus.draft, None)
    case sni                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01c1), MulticodecStatus.draft, Some("Server Name Indication RFC 6066 § 3"))
    case noise                          extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01c6), MulticodecStatus.draft, None)
    case shs                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01c8), MulticodecStatus.draft, Some("Secure Scuttlebutt - Secret Handshake Stream"))
    case quic                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01cc), MulticodecStatus.permanent, None)
    case quic_v1                        extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01cd), MulticodecStatus.permanent, None)
    case webtransport                   extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01d1), MulticodecStatus.draft, None)
    case certhash                       extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01d2), MulticodecStatus.draft, Some("TLS certificate's fingerprint as a multihash"))
    case ws                             extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01dd), MulticodecStatus.permanent, None)
    case wss                            extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01de), MulticodecStatus.permanent, None)
    case p2p_websocket_star             extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01df), MulticodecStatus.permanent, None)
    case http                           extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01e0), MulticodecStatus.draft, None)
    case http_path                      extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x01e1), MulticodecStatus.draft, Some("Percent-encoded path to an HTTP resource"))
    case swhid_1_snp                    extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x01f0), MulticodecStatus.draft, Some("SoftWare Heritage persistent IDentifier version 1 snapshot"))
    case json                           extends Multicodec(MulticodecTag.ipld, VarInt.encode(0x0200), MulticodecStatus.permanent, Some("JSON (UTF-8-encoded)"))
    case messagepack                    extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x0201), MulticodecStatus.draft, Some("MessagePack"))
    case car                            extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x0202), MulticodecStatus.draft, Some("Content Addressable aRchive (CAR)"))
    case ipns_record                    extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x0300), MulticodecStatus.permanent, Some("Signed IPNS Record"))
    case libp2p_peer_record             extends Multicodec(MulticodecTag.libp2p, VarInt.encode(0x0301), MulticodecStatus.permanent, Some("libp2p peer record type"))
    case libp2p_relay_rsvp              extends Multicodec(MulticodecTag.libp2p, VarInt.encode(0x0302), MulticodecStatus.permanent, Some("libp2p relay reservation voucher"))
    case memorytransport                extends Multicodec(MulticodecTag.libp2p, VarInt.encode(0x0309), MulticodecStatus.permanent, Some("in memory transport for self-dialing and testing; arbitrary"))
    case car_index_sorted               extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x0400), MulticodecStatus.draft, Some("CARv2 IndexSorted index format"))
    case car_multihash_index_sorted     extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x0401), MulticodecStatus.draft, Some("CARv2 MultihashIndexSorted index format"))
    case transport_bitswap              extends Multicodec(MulticodecTag.transport, VarInt.encode(0x0900), MulticodecStatus.draft, Some("Bitswap datatransfer"))
    case transport_graphsync_filecoinv1 extends Multicodec(MulticodecTag.transport, VarInt.encode(0x0910), MulticodecStatus.draft, Some("Filecoin graphsync datatransfer"))
    case transport_ipfs_gateway_http    extends Multicodec(MulticodecTag.transport, VarInt.encode(0x0920), MulticodecStatus.draft, Some("HTTP IPFS Gateway trustless datatransfer"))
    case multidid                       extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x0d1d), MulticodecStatus.draft, Some("Compact encoding for Decentralized Identifers"))
    case sha2_256_trunc254_padded       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1012), MulticodecStatus.permanent, Some("SHA2-256 with the two most significant bits from the last byte zeroed (as via a mask with 0b00111111) - used for proving trees as in Filecoin"))
    case sha2_224                       extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1013), MulticodecStatus.permanent, Some("aka SHA-224; as specified by FIPS 180-4."))
    case sha2_512_224                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1014), MulticodecStatus.permanent, Some("aka SHA-512/224; as specified by FIPS 180-4."))
    case sha2_512_256                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1015), MulticodecStatus.permanent, Some("aka SHA-512/256; as specified by FIPS 180-4."))
    case murmur3_x64_128                extends Multicodec(MulticodecTag.hash, VarInt.encode(0x1022), MulticodecStatus.draft, None)
    case ripemd_128                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1052), MulticodecStatus.draft, None)
    case ripemd_160                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1053), MulticodecStatus.draft, None)
    case ripemd_256                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1054), MulticodecStatus.draft, None)
    case ripemd_320                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1055), MulticodecStatus.draft, None)
    case x11                            extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1100), MulticodecStatus.draft, None)
    case p256_pub                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1200), MulticodecStatus.draft, Some("P-256 public Key (compressed)"))
    case p384_pub                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1201), MulticodecStatus.draft, Some("P-384 public Key (compressed)"))
    case p521_pub                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1202), MulticodecStatus.draft, Some("P-521 public Key (compressed)"))
    case ed448_pub                      extends Multicodec(MulticodecTag.key, VarInt.encode(0x1203), MulticodecStatus.draft, Some("Ed448 public Key"))
    case x448_pub                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1204), MulticodecStatus.draft, Some("X448 public Key"))
    case rsa_pub                        extends Multicodec(MulticodecTag.key, VarInt.encode(0x1205), MulticodecStatus.draft, Some("RSA public key. DER-encoded ASN.1 type RSAPublicKey according to IETF RFC 8017 (PKCS #1)"))
    case sm2_pub                        extends Multicodec(MulticodecTag.key, VarInt.encode(0x1206), MulticodecStatus.draft, Some("SM2 public key (compressed)"))
    case vlad                           extends Multicodec(MulticodecTag.vlad, VarInt.encode(0x1207), MulticodecStatus.draft, Some("Verifiable Long-lived ADdress"))
    case provenance_log                 extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x1208), MulticodecStatus.draft, Some("Verifiable and permissioned append-only log"))
    case provenance_log_entry           extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x1209), MulticodecStatus.draft, Some("Verifiable and permissioned append-only log entry"))
    case provenance_log_script          extends Multicodec(MulticodecTag.serialization, VarInt.encode(0x120a), MulticodecStatus.draft, Some("Verifiable and permissioned append-only log script"))
    case mlkem_512_pub                  extends Multicodec(MulticodecTag.key, VarInt.encode(0x120b), MulticodecStatus.draft, Some("ML-KEM 512 public key; as specified by FIPS 203"))
    case mlkem_768_pub                  extends Multicodec(MulticodecTag.key, VarInt.encode(0x120c), MulticodecStatus.draft, Some("ML-KEM 768 public key; as specified by FIPS 203"))
    case mlkem_1024_pub                 extends Multicodec(MulticodecTag.key, VarInt.encode(0x120d), MulticodecStatus.draft, Some("ML-KEM 1024 public key; as specified by FIPS 203"))
    case multisig                       extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x1239), MulticodecStatus.draft, Some("Digital signature multiformat"))
    case multikey                       extends Multicodec(MulticodecTag.multiformat, VarInt.encode(0x123a), MulticodecStatus.draft, Some("Encryption key multiformat"))
    case nonce                          extends Multicodec(MulticodecTag.nonce, VarInt.encode(0x123b), MulticodecStatus.draft, Some("Nonce random value"))
    case ed25519_priv                   extends Multicodec(MulticodecTag.key, VarInt.encode(0x1300), MulticodecStatus.draft, Some("Ed25519 private key"))
    case secp256k1_priv                 extends Multicodec(MulticodecTag.key, VarInt.encode(0x1301), MulticodecStatus.draft, Some("Secp256k1 private key"))
    case x25519_priv                    extends Multicodec(MulticodecTag.key, VarInt.encode(0x1302), MulticodecStatus.draft, Some("Curve25519 private key"))
    case sr25519_priv                   extends Multicodec(MulticodecTag.key, VarInt.encode(0x1303), MulticodecStatus.draft, Some("Sr25519 private key"))
    case rsa_priv                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1305), MulticodecStatus.draft, Some("RSA private key"))
    case p256_priv                      extends Multicodec(MulticodecTag.key, VarInt.encode(0x1306), MulticodecStatus.draft, Some("P-256 private key"))
    case p384_priv                      extends Multicodec(MulticodecTag.key, VarInt.encode(0x1307), MulticodecStatus.draft, Some("P-384 private key"))
    case p521_priv                      extends Multicodec(MulticodecTag.key, VarInt.encode(0x1308), MulticodecStatus.draft, Some("P-521 private key"))
    case bls12_381_g1_priv              extends Multicodec(MulticodecTag.key, VarInt.encode(0x1309), MulticodecStatus.draft, Some("BLS12-381 G1 private key"))
    case bls12_381_g2_priv              extends Multicodec(MulticodecTag.key, VarInt.encode(0x130a), MulticodecStatus.draft, Some("BLS12-381 G2 private key"))
    case bls12_381_g1g2_priv            extends Multicodec(MulticodecTag.key, VarInt.encode(0x130b), MulticodecStatus.draft, Some("BLS12-381 G1 and G2 private key"))
    case bls12_381_g1_pub_share         extends Multicodec(MulticodecTag.key, VarInt.encode(0x130c), MulticodecStatus.draft, Some("BLS12-381 G1 public key share"))
    case bls12_381_g2_pub_share         extends Multicodec(MulticodecTag.key, VarInt.encode(0x130d), MulticodecStatus.draft, Some("BLS12-381 G2 public key share"))
    case bls12_381_g1_priv_share        extends Multicodec(MulticodecTag.key, VarInt.encode(0x130e), MulticodecStatus.draft, Some("BLS12-381 G1 private key share"))
    case bls12_381_g2_priv_share        extends Multicodec(MulticodecTag.key, VarInt.encode(0x130f), MulticodecStatus.draft, Some("BLS12-381 G2 private key share"))
    case sm2_priv                       extends Multicodec(MulticodecTag.key, VarInt.encode(0x1310), MulticodecStatus.draft, Some("SM2 private key"))
    case lamport_sha3_512_pub           extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a14), MulticodecStatus.draft, Some("Lamport public key based on SHA3-512"))
    case lamport_sha3_384_pub           extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a15), MulticodecStatus.draft, Some("Lamport public key based on SHA3-384"))
    case lamport_sha3_256_pub           extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a16), MulticodecStatus.draft, Some("Lamport public key based on SHA3-256"))
    case lamport_sha3_512_priv          extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a24), MulticodecStatus.draft, Some("Lamport private key based on SHA3-512"))
    case lamport_sha3_384_priv          extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a25), MulticodecStatus.draft, Some("Lamport private key based on SHA3-384"))
    case lamport_sha3_256_priv          extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a26), MulticodecStatus.draft, Some("Lamport private key based on SHA3-256"))
    case lamport_sha3_512_priv_share    extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a34), MulticodecStatus.draft, Some("Lamport private key share based on SHA3-512 and split with Shamir gf256"))
    case lamport_sha3_384_priv_share    extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a35), MulticodecStatus.draft, Some("Lamport private key share based on SHA3-384 and split with Shamir gf256"))
    case lamport_sha3_256_priv_share    extends Multicodec(MulticodecTag.key, VarInt.encode(0x1a36), MulticodecStatus.draft, Some("Lamport private key share based on SHA3-256 and split with Shamir gf256"))
    case lamport_sha3_512_sig           extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a44), MulticodecStatus.draft, Some("Lamport signature based on SHA3-512"))
    case lamport_sha3_384_sig           extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a45), MulticodecStatus.draft, Some("Lamport signature based on SHA3-384"))
    case lamport_sha3_256_sig           extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a46), MulticodecStatus.draft, Some("Lamport signature based on SHA3-256"))
    case lamport_sha3_512_sig_share     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a54), MulticodecStatus.draft, Some("Lamport signature share based on SHA3-512 and split with Shamir gf256"))
    case lamport_sha3_384_sig_share     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a55), MulticodecStatus.draft, Some("Lamport signature share based on SHA3-384 and split with Shamir gf256"))
    case lamport_sha3_256_sig_share     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0x1a56), MulticodecStatus.draft, Some("Lamport signature share based on SHA3-256 and split with Shamir gf256"))
    case kangarootwelve                 extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x1d01), MulticodecStatus.draft, Some("KangarooTwelve is an extendable-output hash function based on Keccak-p"))
    case aes_gcm_256                    extends Multicodec(MulticodecTag.encryption, VarInt.encode(0x2000), MulticodecStatus.draft, Some("AES Galois/Counter Mode with 256-bit key and 12-byte IV"))
    case silverpine                     extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x3f42), MulticodecStatus.draft, Some("Experimental QUIC over yggdrasil and ironwood routing protocol"))
    case sm3_256                        extends Multicodec(MulticodecTag.multihash, VarInt.encode(0x534d), MulticodecStatus.draft, None)
    case sha256a                        extends Multicodec(MulticodecTag.hash, VarInt.encode(0x7012), MulticodecStatus.draft, Some("The sum of multiple sha2-256 hashes; as specified by Ceramic CIP-124."))
    case chacha20_poly1305              extends Multicodec(MulticodecTag.multikey, VarInt.encode(0xa000), MulticodecStatus.draft, Some("ChaCha20_Poly1305 encryption scheme"))
    case blake2b_8                      extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb201), MulticodecStatus.draft, Some("Blake2b consists of 64 output lengths that give different hashes"))
    case blake2b_16                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb202), MulticodecStatus.draft, None)
    case blake2b_24                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb203), MulticodecStatus.draft, None)
    case blake2b_32                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb204), MulticodecStatus.draft, None)
    case blake2b_40                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb205), MulticodecStatus.draft, None)
    case blake2b_48                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb206), MulticodecStatus.draft, None)
    case blake2b_56                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb207), MulticodecStatus.draft, None)
    case blake2b_64                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb208), MulticodecStatus.draft, None)
    case blake2b_72                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb209), MulticodecStatus.draft, None)
    case blake2b_80                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20a), MulticodecStatus.draft, None)
    case blake2b_88                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20b), MulticodecStatus.draft, None)
    case blake2b_96                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20c), MulticodecStatus.draft, None)
    case blake2b_104                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20d), MulticodecStatus.draft, None)
    case blake2b_112                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20e), MulticodecStatus.draft, None)
    case blake2b_120                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb20f), MulticodecStatus.draft, None)
    case blake2b_128                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb210), MulticodecStatus.draft, None)
    case blake2b_136                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb211), MulticodecStatus.draft, None)
    case blake2b_144                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb212), MulticodecStatus.draft, None)
    case blake2b_152                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb213), MulticodecStatus.draft, None)
    case blake2b_160                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb214), MulticodecStatus.draft, None)
    case blake2b_168                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb215), MulticodecStatus.draft, None)
    case blake2b_176                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb216), MulticodecStatus.draft, None)
    case blake2b_184                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb217), MulticodecStatus.draft, None)
    case blake2b_192                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb218), MulticodecStatus.draft, None)
    case blake2b_200                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb219), MulticodecStatus.draft, None)
    case blake2b_208                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21a), MulticodecStatus.draft, None)
    case blake2b_216                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21b), MulticodecStatus.draft, None)
    case blake2b_224                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21c), MulticodecStatus.draft, None)
    case blake2b_232                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21d), MulticodecStatus.draft, None)
    case blake2b_240                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21e), MulticodecStatus.draft, None)
    case blake2b_248                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb21f), MulticodecStatus.draft, None)
    case blake2b_256                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb220), MulticodecStatus.permanent, None)
    case blake2b_264                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb221), MulticodecStatus.draft, None)
    case blake2b_272                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb222), MulticodecStatus.draft, None)
    case blake2b_280                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb223), MulticodecStatus.draft, None)
    case blake2b_288                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb224), MulticodecStatus.draft, None)
    case blake2b_296                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb225), MulticodecStatus.draft, None)
    case blake2b_304                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb226), MulticodecStatus.draft, None)
    case blake2b_312                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb227), MulticodecStatus.draft, None)
    case blake2b_320                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb228), MulticodecStatus.draft, None)
    case blake2b_328                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb229), MulticodecStatus.draft, None)
    case blake2b_336                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22a), MulticodecStatus.draft, None)
    case blake2b_344                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22b), MulticodecStatus.draft, None)
    case blake2b_352                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22c), MulticodecStatus.draft, None)
    case blake2b_360                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22d), MulticodecStatus.draft, None)
    case blake2b_368                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22e), MulticodecStatus.draft, None)
    case blake2b_376                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb22f), MulticodecStatus.draft, None)
    case blake2b_384                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb230), MulticodecStatus.draft, None)
    case blake2b_392                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb231), MulticodecStatus.draft, None)
    case blake2b_400                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb232), MulticodecStatus.draft, None)
    case blake2b_408                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb233), MulticodecStatus.draft, None)
    case blake2b_416                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb234), MulticodecStatus.draft, None)
    case blake2b_424                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb235), MulticodecStatus.draft, None)
    case blake2b_432                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb236), MulticodecStatus.draft, None)
    case blake2b_440                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb237), MulticodecStatus.draft, None)
    case blake2b_448                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb238), MulticodecStatus.draft, None)
    case blake2b_456                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb239), MulticodecStatus.draft, None)
    case blake2b_464                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23a), MulticodecStatus.draft, None)
    case blake2b_472                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23b), MulticodecStatus.draft, None)
    case blake2b_480                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23c), MulticodecStatus.draft, None)
    case blake2b_488                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23d), MulticodecStatus.draft, None)
    case blake2b_496                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23e), MulticodecStatus.draft, None)
    case blake2b_504                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb23f), MulticodecStatus.draft, None)
    case blake2b_512                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb240), MulticodecStatus.draft, None)
    case blake2s_8                      extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb241), MulticodecStatus.draft, Some("Blake2s consists of 32 output lengths that give different hashes"))
    case blake2s_16                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb242), MulticodecStatus.draft, None)
    case blake2s_24                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb243), MulticodecStatus.draft, None)
    case blake2s_32                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb244), MulticodecStatus.draft, None)
    case blake2s_40                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb245), MulticodecStatus.draft, None)
    case blake2s_48                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb246), MulticodecStatus.draft, None)
    case blake2s_56                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb247), MulticodecStatus.draft, None)
    case blake2s_64                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb248), MulticodecStatus.draft, None)
    case blake2s_72                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb249), MulticodecStatus.draft, None)
    case blake2s_80                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24a), MulticodecStatus.draft, None)
    case blake2s_88                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24b), MulticodecStatus.draft, None)
    case blake2s_96                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24c), MulticodecStatus.draft, None)
    case blake2s_104                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24d), MulticodecStatus.draft, None)
    case blake2s_112                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24e), MulticodecStatus.draft, None)
    case blake2s_120                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb24f), MulticodecStatus.draft, None)
    case blake2s_128                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb250), MulticodecStatus.draft, None)
    case blake2s_136                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb251), MulticodecStatus.draft, None)
    case blake2s_144                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb252), MulticodecStatus.draft, None)
    case blake2s_152                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb253), MulticodecStatus.draft, None)
    case blake2s_160                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb254), MulticodecStatus.draft, None)
    case blake2s_168                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb255), MulticodecStatus.draft, None)
    case blake2s_176                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb256), MulticodecStatus.draft, None)
    case blake2s_184                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb257), MulticodecStatus.draft, None)
    case blake2s_192                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb258), MulticodecStatus.draft, None)
    case blake2s_200                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb259), MulticodecStatus.draft, None)
    case blake2s_208                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25a), MulticodecStatus.draft, None)
    case blake2s_216                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25b), MulticodecStatus.draft, None)
    case blake2s_224                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25c), MulticodecStatus.draft, None)
    case blake2s_232                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25d), MulticodecStatus.draft, None)
    case blake2s_240                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25e), MulticodecStatus.draft, None)
    case blake2s_248                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb25f), MulticodecStatus.draft, None)
    case blake2s_256                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb260), MulticodecStatus.draft, None)
    case skein256_8                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb301), MulticodecStatus.draft, Some("Skein256 consists of 32 output lengths that give different hashes"))
    case skein256_16                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb302), MulticodecStatus.draft, None)
    case skein256_24                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb303), MulticodecStatus.draft, None)
    case skein256_32                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb304), MulticodecStatus.draft, None)
    case skein256_40                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb305), MulticodecStatus.draft, None)
    case skein256_48                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb306), MulticodecStatus.draft, None)
    case skein256_56                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb307), MulticodecStatus.draft, None)
    case skein256_64                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb308), MulticodecStatus.draft, None)
    case skein256_72                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb309), MulticodecStatus.draft, None)
    case skein256_80                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30a), MulticodecStatus.draft, None)
    case skein256_88                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30b), MulticodecStatus.draft, None)
    case skein256_96                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30c), MulticodecStatus.draft, None)
    case skein256_104                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30d), MulticodecStatus.draft, None)
    case skein256_112                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30e), MulticodecStatus.draft, None)
    case skein256_120                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb30f), MulticodecStatus.draft, None)
    case skein256_128                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb310), MulticodecStatus.draft, None)
    case skein256_136                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb311), MulticodecStatus.draft, None)
    case skein256_144                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb312), MulticodecStatus.draft, None)
    case skein256_152                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb313), MulticodecStatus.draft, None)
    case skein256_160                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb314), MulticodecStatus.draft, None)
    case skein256_168                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb315), MulticodecStatus.draft, None)
    case skein256_176                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb316), MulticodecStatus.draft, None)
    case skein256_184                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb317), MulticodecStatus.draft, None)
    case skein256_192                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb318), MulticodecStatus.draft, None)
    case skein256_200                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb319), MulticodecStatus.draft, None)
    case skein256_208                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31a), MulticodecStatus.draft, None)
    case skein256_216                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31b), MulticodecStatus.draft, None)
    case skein256_224                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31c), MulticodecStatus.draft, None)
    case skein256_232                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31d), MulticodecStatus.draft, None)
    case skein256_240                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31e), MulticodecStatus.draft, None)
    case skein256_248                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb31f), MulticodecStatus.draft, None)
    case skein256_256                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb320), MulticodecStatus.draft, None)
    case skein512_8                     extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb321), MulticodecStatus.draft, Some("Skein512 consists of 64 output lengths that give different hashes"))
    case skein512_16                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb322), MulticodecStatus.draft, None)
    case skein512_24                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb323), MulticodecStatus.draft, None)
    case skein512_32                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb324), MulticodecStatus.draft, None)
    case skein512_40                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb325), MulticodecStatus.draft, None)
    case skein512_48                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb326), MulticodecStatus.draft, None)
    case skein512_56                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb327), MulticodecStatus.draft, None)
    case skein512_64                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb328), MulticodecStatus.draft, None)
    case skein512_72                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb329), MulticodecStatus.draft, None)
    case skein512_80                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32a), MulticodecStatus.draft, None)
    case skein512_88                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32b), MulticodecStatus.draft, None)
    case skein512_96                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32c), MulticodecStatus.draft, None)
    case skein512_104                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32d), MulticodecStatus.draft, None)
    case skein512_112                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32e), MulticodecStatus.draft, None)
    case skein512_120                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb32f), MulticodecStatus.draft, None)
    case skein512_128                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb330), MulticodecStatus.draft, None)
    case skein512_136                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb331), MulticodecStatus.draft, None)
    case skein512_144                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb332), MulticodecStatus.draft, None)
    case skein512_152                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb333), MulticodecStatus.draft, None)
    case skein512_160                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb334), MulticodecStatus.draft, None)
    case skein512_168                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb335), MulticodecStatus.draft, None)
    case skein512_176                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb336), MulticodecStatus.draft, None)
    case skein512_184                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb337), MulticodecStatus.draft, None)
    case skein512_192                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb338), MulticodecStatus.draft, None)
    case skein512_200                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb339), MulticodecStatus.draft, None)
    case skein512_208                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33a), MulticodecStatus.draft, None)
    case skein512_216                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33b), MulticodecStatus.draft, None)
    case skein512_224                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33c), MulticodecStatus.draft, None)
    case skein512_232                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33d), MulticodecStatus.draft, None)
    case skein512_240                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33e), MulticodecStatus.draft, None)
    case skein512_248                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb33f), MulticodecStatus.draft, None)
    case skein512_256                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb340), MulticodecStatus.draft, None)
    case skein512_264                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb341), MulticodecStatus.draft, None)
    case skein512_272                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb342), MulticodecStatus.draft, None)
    case skein512_280                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb343), MulticodecStatus.draft, None)
    case skein512_288                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb344), MulticodecStatus.draft, None)
    case skein512_296                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb345), MulticodecStatus.draft, None)
    case skein512_304                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb346), MulticodecStatus.draft, None)
    case skein512_312                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb347), MulticodecStatus.draft, None)
    case skein512_320                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb348), MulticodecStatus.draft, None)
    case skein512_328                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb349), MulticodecStatus.draft, None)
    case skein512_336                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34a), MulticodecStatus.draft, None)
    case skein512_344                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34b), MulticodecStatus.draft, None)
    case skein512_352                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34c), MulticodecStatus.draft, None)
    case skein512_360                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34d), MulticodecStatus.draft, None)
    case skein512_368                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34e), MulticodecStatus.draft, None)
    case skein512_376                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb34f), MulticodecStatus.draft, None)
    case skein512_384                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb350), MulticodecStatus.draft, None)
    case skein512_392                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb351), MulticodecStatus.draft, None)
    case skein512_400                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb352), MulticodecStatus.draft, None)
    case skein512_408                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb353), MulticodecStatus.draft, None)
    case skein512_416                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb354), MulticodecStatus.draft, None)
    case skein512_424                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb355), MulticodecStatus.draft, None)
    case skein512_432                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb356), MulticodecStatus.draft, None)
    case skein512_440                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb357), MulticodecStatus.draft, None)
    case skein512_448                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb358), MulticodecStatus.draft, None)
    case skein512_456                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb359), MulticodecStatus.draft, None)
    case skein512_464                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35a), MulticodecStatus.draft, None)
    case skein512_472                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35b), MulticodecStatus.draft, None)
    case skein512_480                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35c), MulticodecStatus.draft, None)
    case skein512_488                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35d), MulticodecStatus.draft, None)
    case skein512_496                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35e), MulticodecStatus.draft, None)
    case skein512_504                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb35f), MulticodecStatus.draft, None)
    case skein512_512                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb360), MulticodecStatus.draft, None)
    case skein1024_8                    extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb361), MulticodecStatus.draft, Some("Skein1024 consists of 128 output lengths that give different hashes"))
    case skein1024_16                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb362), MulticodecStatus.draft, None)
    case skein1024_24                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb363), MulticodecStatus.draft, None)
    case skein1024_32                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb364), MulticodecStatus.draft, None)
    case skein1024_40                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb365), MulticodecStatus.draft, None)
    case skein1024_48                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb366), MulticodecStatus.draft, None)
    case skein1024_56                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb367), MulticodecStatus.draft, None)
    case skein1024_64                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb368), MulticodecStatus.draft, None)
    case skein1024_72                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb369), MulticodecStatus.draft, None)
    case skein1024_80                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36a), MulticodecStatus.draft, None)
    case skein1024_88                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36b), MulticodecStatus.draft, None)
    case skein1024_96                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36c), MulticodecStatus.draft, None)
    case skein1024_104                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36d), MulticodecStatus.draft, None)
    case skein1024_112                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36e), MulticodecStatus.draft, None)
    case skein1024_120                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb36f), MulticodecStatus.draft, None)
    case skein1024_128                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb370), MulticodecStatus.draft, None)
    case skein1024_136                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb371), MulticodecStatus.draft, None)
    case skein1024_144                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb372), MulticodecStatus.draft, None)
    case skein1024_152                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb373), MulticodecStatus.draft, None)
    case skein1024_160                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb374), MulticodecStatus.draft, None)
    case skein1024_168                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb375), MulticodecStatus.draft, None)
    case skein1024_176                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb376), MulticodecStatus.draft, None)
    case skein1024_184                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb377), MulticodecStatus.draft, None)
    case skein1024_192                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb378), MulticodecStatus.draft, None)
    case skein1024_200                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb379), MulticodecStatus.draft, None)
    case skein1024_208                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37a), MulticodecStatus.draft, None)
    case skein1024_216                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37b), MulticodecStatus.draft, None)
    case skein1024_224                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37c), MulticodecStatus.draft, None)
    case skein1024_232                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37d), MulticodecStatus.draft, None)
    case skein1024_240                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37e), MulticodecStatus.draft, None)
    case skein1024_248                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb37f), MulticodecStatus.draft, None)
    case skein1024_256                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb380), MulticodecStatus.draft, None)
    case skein1024_264                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb381), MulticodecStatus.draft, None)
    case skein1024_272                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb382), MulticodecStatus.draft, None)
    case skein1024_280                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb383), MulticodecStatus.draft, None)
    case skein1024_288                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb384), MulticodecStatus.draft, None)
    case skein1024_296                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb385), MulticodecStatus.draft, None)
    case skein1024_304                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb386), MulticodecStatus.draft, None)
    case skein1024_312                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb387), MulticodecStatus.draft, None)
    case skein1024_320                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb388), MulticodecStatus.draft, None)
    case skein1024_328                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb389), MulticodecStatus.draft, None)
    case skein1024_336                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38a), MulticodecStatus.draft, None)
    case skein1024_344                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38b), MulticodecStatus.draft, None)
    case skein1024_352                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38c), MulticodecStatus.draft, None)
    case skein1024_360                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38d), MulticodecStatus.draft, None)
    case skein1024_368                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38e), MulticodecStatus.draft, None)
    case skein1024_376                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb38f), MulticodecStatus.draft, None)
    case skein1024_384                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb390), MulticodecStatus.draft, None)
    case skein1024_392                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb391), MulticodecStatus.draft, None)
    case skein1024_400                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb392), MulticodecStatus.draft, None)
    case skein1024_408                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb393), MulticodecStatus.draft, None)
    case skein1024_416                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb394), MulticodecStatus.draft, None)
    case skein1024_424                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb395), MulticodecStatus.draft, None)
    case skein1024_432                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb396), MulticodecStatus.draft, None)
    case skein1024_440                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb397), MulticodecStatus.draft, None)
    case skein1024_448                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb398), MulticodecStatus.draft, None)
    case skein1024_456                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb399), MulticodecStatus.draft, None)
    case skein1024_464                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39a), MulticodecStatus.draft, None)
    case skein1024_472                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39b), MulticodecStatus.draft, None)
    case skein1024_480                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39c), MulticodecStatus.draft, None)
    case skein1024_488                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39d), MulticodecStatus.draft, None)
    case skein1024_496                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39e), MulticodecStatus.draft, None)
    case skein1024_504                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb39f), MulticodecStatus.draft, None)
    case skein1024_512                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a0), MulticodecStatus.draft, None)
    case skein1024_520                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a1), MulticodecStatus.draft, None)
    case skein1024_528                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a2), MulticodecStatus.draft, None)
    case skein1024_536                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a3), MulticodecStatus.draft, None)
    case skein1024_544                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a4), MulticodecStatus.draft, None)
    case skein1024_552                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a5), MulticodecStatus.draft, None)
    case skein1024_560                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a6), MulticodecStatus.draft, None)
    case skein1024_568                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a7), MulticodecStatus.draft, None)
    case skein1024_576                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a8), MulticodecStatus.draft, None)
    case skein1024_584                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3a9), MulticodecStatus.draft, None)
    case skein1024_592                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3aa), MulticodecStatus.draft, None)
    case skein1024_600                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ab), MulticodecStatus.draft, None)
    case skein1024_608                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ac), MulticodecStatus.draft, None)
    case skein1024_616                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ad), MulticodecStatus.draft, None)
    case skein1024_624                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ae), MulticodecStatus.draft, None)
    case skein1024_632                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3af), MulticodecStatus.draft, None)
    case skein1024_640                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b0), MulticodecStatus.draft, None)
    case skein1024_648                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b1), MulticodecStatus.draft, None)
    case skein1024_656                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b2), MulticodecStatus.draft, None)
    case skein1024_664                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b3), MulticodecStatus.draft, None)
    case skein1024_672                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b4), MulticodecStatus.draft, None)
    case skein1024_680                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b5), MulticodecStatus.draft, None)
    case skein1024_688                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b6), MulticodecStatus.draft, None)
    case skein1024_696                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b7), MulticodecStatus.draft, None)
    case skein1024_704                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b8), MulticodecStatus.draft, None)
    case skein1024_712                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3b9), MulticodecStatus.draft, None)
    case skein1024_720                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ba), MulticodecStatus.draft, None)
    case skein1024_728                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3bb), MulticodecStatus.draft, None)
    case skein1024_736                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3bc), MulticodecStatus.draft, None)
    case skein1024_744                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3bd), MulticodecStatus.draft, None)
    case skein1024_752                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3be), MulticodecStatus.draft, None)
    case skein1024_760                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3bf), MulticodecStatus.draft, None)
    case skein1024_768                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c0), MulticodecStatus.draft, None)
    case skein1024_776                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c1), MulticodecStatus.draft, None)
    case skein1024_784                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c2), MulticodecStatus.draft, None)
    case skein1024_792                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c3), MulticodecStatus.draft, None)
    case skein1024_800                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c4), MulticodecStatus.draft, None)
    case skein1024_808                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c5), MulticodecStatus.draft, None)
    case skein1024_816                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c6), MulticodecStatus.draft, None)
    case skein1024_824                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c7), MulticodecStatus.draft, None)
    case skein1024_832                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c8), MulticodecStatus.draft, None)
    case skein1024_840                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3c9), MulticodecStatus.draft, None)
    case skein1024_848                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ca), MulticodecStatus.draft, None)
    case skein1024_856                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3cb), MulticodecStatus.draft, None)
    case skein1024_864                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3cc), MulticodecStatus.draft, None)
    case skein1024_872                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3cd), MulticodecStatus.draft, None)
    case skein1024_880                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3ce), MulticodecStatus.draft, None)
    case skein1024_888                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3cf), MulticodecStatus.draft, None)
    case skein1024_896                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d0), MulticodecStatus.draft, None)
    case skein1024_904                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d1), MulticodecStatus.draft, None)
    case skein1024_912                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d2), MulticodecStatus.draft, None)
    case skein1024_920                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d3), MulticodecStatus.draft, None)
    case skein1024_928                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d4), MulticodecStatus.draft, None)
    case skein1024_936                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d5), MulticodecStatus.draft, None)
    case skein1024_944                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d6), MulticodecStatus.draft, None)
    case skein1024_952                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d7), MulticodecStatus.draft, None)
    case skein1024_960                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d8), MulticodecStatus.draft, None)
    case skein1024_968                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3d9), MulticodecStatus.draft, None)
    case skein1024_976                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3da), MulticodecStatus.draft, None)
    case skein1024_984                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3db), MulticodecStatus.draft, None)
    case skein1024_992                  extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3dc), MulticodecStatus.draft, None)
    case skein1024_1000                 extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3dd), MulticodecStatus.draft, None)
    case skein1024_1008                 extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3de), MulticodecStatus.draft, None)
    case skein1024_1016                 extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3df), MulticodecStatus.draft, None)
    case skein1024_1024                 extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb3e0), MulticodecStatus.draft, None)
    case xxh_32                         extends Multicodec(MulticodecTag.hash, VarInt.encode(0xb3e1), MulticodecStatus.draft, Some("Extremely fast non-cryptographic hash algorithm"))
    case xxh_64                         extends Multicodec(MulticodecTag.hash, VarInt.encode(0xb3e2), MulticodecStatus.draft, Some("Extremely fast non-cryptographic hash algorithm"))
    case xxh3_64                        extends Multicodec(MulticodecTag.hash, VarInt.encode(0xb3e3), MulticodecStatus.draft, Some("Extremely fast non-cryptographic hash algorithm"))
    case xxh3_128                       extends Multicodec(MulticodecTag.hash, VarInt.encode(0xb3e4), MulticodecStatus.draft, Some("Extremely fast non-cryptographic hash algorithm"))
    case poseidon_bls12_381_a2_fc1      extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb401), MulticodecStatus.permanent, Some("Poseidon using BLS12-381 and arity of 2 with Filecoin parameters"))
    case poseidon_bls12_381_a2_fc1_sc   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb402), MulticodecStatus.draft, Some("Poseidon using BLS12-381 and arity of 2 with Filecoin parameters - high-security variant"))
    case rdfc_1                         extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xb403), MulticodecStatus.draft, Some("The result of canonicalizing an input according to RDFC-1.0 and then expressing its hash value as a multihash value."))
    case ssz                            extends Multicodec(MulticodecTag.serialization, VarInt.encode(0xb501), MulticodecStatus.draft, Some("SimpleSerialize (SSZ) serialization"))
    case ssz_sha2_256_bmt               extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb502), MulticodecStatus.draft, Some("SSZ Merkle tree root using SHA2-256 as the hashing function and SSZ serialization for the block binary"))
    case sha2_256_chunked               extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xb510), MulticodecStatus.draft, Some("Hash of concatenated SHA2-256 digests of 8*2^n MiB source chunks; n = ceil(log2(source_size/(10^4 * 8MiB)))"))
    case json_jcs                       extends Multicodec(MulticodecTag.ipld, VarInt.encode(0xb601), MulticodecStatus.draft, Some("The result of canonicalizing an input according to JCS - JSON Canonicalisation Scheme (RFC 8785)"))
    case iscc                           extends Multicodec(MulticodecTag.softhash, VarInt.encode(0xcc01), MulticodecStatus.draft, Some("ISCC (International Standard Content Code) - similarity preserving hash"))
    case zeroxcert_imprint_256          extends Multicodec(MulticodecTag.zeroxcert, VarInt.encode(0xce11), MulticodecStatus.draft, Some("0xcert Asset Imprint (root hash)"))
    case nonstandard_sig                extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd000), MulticodecStatus.deprecated, Some("Namespace for all not yet standard signature algorithms"))
    case bcrypt_pbkdf                   extends Multicodec(MulticodecTag.multihash, VarInt.encode(0xd00d), MulticodecStatus.draft, Some("Bcrypt-PBKDF key derivation function"))
    case es256k                         extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd0e7), MulticodecStatus.draft, Some("ES256K Signature Algorithm (secp256k1)"))
    case bls12_381_g1_sig               extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd0ea), MulticodecStatus.draft, Some("G1 signature for BLS12-381"))
    case bls12_381_g2_sig               extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd0eb), MulticodecStatus.draft, Some("G2 signature for BLS12-381"))
    case eddsa                          extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd0ed), MulticodecStatus.draft, Some("Edwards-Curve Digital Signature Algorithm"))
    case eip_191                        extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd191), MulticodecStatus.draft, Some("EIP-191 Ethereum Signed Data Standard"))
    case jwk_jcs_pub                    extends Multicodec(MulticodecTag.key, VarInt.encode(0xeb51), MulticodecStatus.draft, Some("JSON object containing only the required members of a JWK (RFC 7518 and RFC 7517) representing the public key. Serialisation based on JCS (RFC 8785)"))
    case fil_commitment_unsealed        extends Multicodec(MulticodecTag.filecoin, VarInt.encode(0xf101), MulticodecStatus.permanent, Some("Filecoin piece or sector data commitment merkle node/root (CommP & CommD)"))
    case fil_commitment_sealed          extends Multicodec(MulticodecTag.filecoin, VarInt.encode(0xf102), MulticodecStatus.permanent, Some("Filecoin sector data commitment merkle node/root - sealed and replicated (CommR)"))
    case shelter_contract_manifest      extends Multicodec(MulticodecTag.shelter, VarInt.encode(0x511e00), MulticodecStatus.draft, Some("Shelter protocol contract manifest"))
    case shelter_contract_text          extends Multicodec(MulticodecTag.shelter, VarInt.encode(0x511e01), MulticodecStatus.draft, Some("Shelter protocol contract text"))
    case shelter_contract_data          extends Multicodec(MulticodecTag.shelter, VarInt.encode(0x511e02), MulticodecStatus.draft, Some("Shelter protocol contract data (contract chain)"))
    case shelter_file_manifest          extends Multicodec(MulticodecTag.shelter, VarInt.encode(0x511e03), MulticodecStatus.draft, Some("Shelter protocol file manifest"))
    case shelter_file_chunk             extends Multicodec(MulticodecTag.shelter, VarInt.encode(0x511e04), MulticodecStatus.draft, Some("Shelter protocol file chunk"))
    case plaintextv2                    extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0x706c61), MulticodecStatus.draft, None)
    case holochain_adr_v0               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0x807124), MulticodecStatus.draft, Some("Holochain v0 address    + 8 R-S (63 x Base-32)"))
    case holochain_adr_v1               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0x817124), MulticodecStatus.draft, Some("Holochain v1 address    + 8 R-S (63 x Base-32)"))
    case holochain_key_v0               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0x947124), MulticodecStatus.draft, Some("Holochain v0 public key + 8 R-S (63 x Base-32)"))
    case holochain_key_v1               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0x957124), MulticodecStatus.draft, Some("Holochain v1 public key + 8 R-S (63 x Base-32)"))
    case holochain_sig_v0               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0xa27124), MulticodecStatus.draft, Some("Holochain v0 signature  + 8 R-S (63 x Base-32)"))
    case holochain_sig_v1               extends Multicodec(MulticodecTag.holochain, VarInt.encode(0xa37124), MulticodecStatus.draft, Some("Holochain v1 signature  + 8 R-S (63 x Base-32)"))
    case skynet_ns                      extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xb19910), MulticodecStatus.draft, Some("Skynet Namespace"))
    case arweave_ns                     extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xb29910), MulticodecStatus.draft, Some("Arweave Namespace"))
    case subspace_ns                    extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xb39910), MulticodecStatus.draft, Some("Subspace Network Namespace"))
    case kumandra_ns                    extends Multicodec(MulticodecTag.namespace, VarInt.encode(0xb49910), MulticodecStatus.draft, Some("Kumandra Network Namespace"))
    case es256                          extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd01200), MulticodecStatus.draft, Some("ES256 Signature Algorithm"))
    case es284                          extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd01201), MulticodecStatus.draft, Some("ES384 Signature Algorithm"))
    case es512                          extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd01202), MulticodecStatus.draft, Some("ES512 Signature Algorithm"))
    case rs256                          extends Multicodec(MulticodecTag.varsig, VarInt.encode(0xd01205), MulticodecStatus.draft, Some("RS256 Signature Algorithm"))
    case es256k_msig                    extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01300), MulticodecStatus.draft, Some("ES256K (secp256k1) Signature as Multisig"))
    case bls12_381_g1_msig              extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01301), MulticodecStatus.draft, Some("G1 signature for BLS-12381-G2 as Multisig"))
    case bls12_381_g2_msig              extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01302), MulticodecStatus.draft, Some("G2 signature for BLS-12381-G1 as Multisig"))
    case eddsa_msig                     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01303), MulticodecStatus.draft, Some("Edwards-Curve Digital Signature as Multisig"))
    case bls12_381_g1_share_msig        extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01304), MulticodecStatus.draft, Some("G1 threshold signature share for BLS-12381-G2 as Multisig"))
    case bls12_381_g2_share_msig        extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01305), MulticodecStatus.draft, Some("G2 threshold signature share for BLS-12381-G1 as Multisig"))
    case lamport_msig                   extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01306), MulticodecStatus.draft, Some("Lamport signature as Multisig"))
    case lamport_share_msig             extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01307), MulticodecStatus.draft, Some("Lamport threshold signature share as Multisig"))
    case es256_msig                     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01308), MulticodecStatus.draft, Some("ECDSA P-256 Signature as Multisig"))
    case es384_msig                     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd01309), MulticodecStatus.draft, Some("ECDSA P-384 Signature as Multisig"))
    case es521_msig                     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd0130a), MulticodecStatus.draft, Some("ECDSA P-521 Signature as Multisig"))
    case rs256_msig                     extends Multicodec(MulticodecTag.multisig, VarInt.encode(0xd0130b), MulticodecStatus.draft, Some("RS256 Signature as Multisig"))
    case scion                          extends Multicodec(MulticodecTag.multiaddr, VarInt.encode(0xd02000), MulticodecStatus.draft, Some("SCION Internet architecture"))
  // generateMulticodec: end //
  // format: on

  sealed trait MulticodecFactory[V]:
    def convert(value: V): Either[String, Multicodec]

  object MulticodecFactory:
    given MulticodecFactory[Multicodec] =
      new MulticodecFactory[Multicodec]:
        def convert(value: Multicodec): Either[String, Multicodec] = Right(value)

    private lazy val codeToCodec: Map[VarInt, Multicodec] =
      Multicodec.values.map(multicodec => multicodec.code -> multicodec).toMap

    given codeFactory: MulticodecFactory[VarInt] =
      new MulticodecFactory[VarInt]:
        def convert(value: VarInt): Either[String, Multicodec] =
          codeToCodec.get(value).toRight(s"Invalid multicodec code: '${value.toHex}'")

    private lazy val nameToCodec: Map[String, Multicodec] =
      Multicodec.values.map(multicodec => multicodec.toString -> multicodec).toMap

    given MulticodecFactory[String] =
      new MulticodecFactory[String]:
        def convert(value: String): Either[String, Multicodec] =
          nameToCodec.get(value).toRight(s"Invalid multicodec name: '$value'")

    given MulticodecFactory[Array[Byte]] =
      new MulticodecFactory[Array[Byte]]:
        def convert(value: Array[Byte]): Either[String, Multicodec] =
          VarInt.sequence(value, 1) match
            case (Array(code), _) => codeFactory.convert(code)
            case _                => Left("Could not extract a varint from bytes")

  //
  // Public object interface for getting a multicodec from a value
  //
  object Multicodec:
    def validated[T](value: T)(using c: MulticodecFactory[T]): Either[String, Multicodec] =
      c.convert(value)
    def ifValid[T](value: T)(using c: MulticodecFactory[T]): Option[Multicodec] =
      c.convert(value).toOption
    def apply[T](value: T)(using c: MulticodecFactory[T]): Multicodec =
      c.convert(value).fold(error => throw MulticodecValidationError(error), x => x)
